version: '3.8'

services:
  web:
    build:
      context: /external/fileconverter
    ports:
      - "5000:5000"
    volumes:
      - /mnt/user/appdata/fileconverter:/app
    restart: unless-stopped
